from flask import Flask
app = Flask(__name__)

import datetime as dt

# load secret key (generated by >>os.urandom(24))
f = open('secret.key' ,'r')
secret_key = f.read()
secret_key = secret_key.decode('string_escape')
f.close()
app.secret_key = secret_key


from app import views

